### ISSUE TITLE
[FEATURE]Add library for LCD Mini Click

### ISSUE THREAD

**Issue by ad-johnson** [MikroElektronika/mikrosdk_click_v2#10]
It would be useful if you could add the library/repository for this click board.  Currently, it doesn't appear to be accessible from this repository

**Comment by MarkoZiv** [comment]
Hello @ad-johnson,
LCD Mini library uses legacy libraries provided in our PRO compilers (SPI LCD module), 
which is not currently supported in mikroSDK v2 and that is the reason why it is not published here yet.

That being said, while going over the project again we came up with a different solution on how to port this click board in mikroSDK v2 to be published as all other click boards (open source).

I will raise the priority on this and let you know once we publish library for this click board officially.
Thank you for reporting.
Regards

**Comment by MarkoZiv** [comment]
LCD mini package and library is available.
https://github.com/MikroElektronika/mikrosdk_click_v2/tree/master/clicks/lcdmini
Issue closed
