### ISSUE TITLE
MCP251863 CLICK Problem

### ISSUE THREAD

**Issue by mickeyl** [MikroElektronika/mikrosdk_click_v2#109]
I can't seem to send or receive CAN frames.
Communication with the controller works fine, but for some reason the transceiver seems to not forward any packages.

I'm using the MCP251863 in the default configuration (40MHz, 3v3, STBY-Selection as prepopulated 0Rs via factory). Is it possible that my board is broken or is there any special dance I need to do to get the transceiver out of standby?

**Comment by StefanFilipovic15** [comment]
Hello Mickey,
Please open a ticket on our [Helpdesk](https://helpdesk.mikroe.com/en-us/1-technical-support)? Our technical support agents will help you test your hardware and troubleshoot the issue.
Kind regards,
Stefan
