### ISSUE TITLE
[Color18] how to decode data from the FIFO of TCS3530?

### ISSUE THREAD

**Issue by listentodella** [MikroElektronika/mikrosdk_click_v2#119]
https://github.com/MikroElektronika/mikrosdk_click_v2/blob/14a87d04931b0e8b3005fa69aa260167f97de2f3/clicks/color18/lib_color18/src/color18.c#L193C1-L214C2

It seems that there is no information about how to parse the fifo data to get als and flicker data in the datasheet.

Could you please guide me on where the basis for this section of code comes from?

**Comment by StefanFilipovic15** [comment]
Hello,

By default, all 8 modulator channels are enabled and written to FIFO; see the MOD_FIFO_DATA_CFGx registers description in the [datasheet](https://look.ams-osram.com/m/273cdc7a1148ba69/original/TCS3530-Fully-Embedded-True-Color-Ambient-Light-Sensor-with-Selective-Flicker-Detection.pdf).
In Figures 8 and 16 you can see the modulator and parameters relation.
For more information about the documentation of the sensor itself, don't hesitate to get in touch with the manufacturer.

Kind regards,
Stefan Filipovic
