### ISSUE TITLE
accel14 include log.h where is log.h?

### ISSUE THREAD

**Issue by KevinBaileyCrum** [MikroElektronika/mikrosdk_click_v2#2]
trying to compile and run the example code to attempt to log data on a pi. cant find where log.h lives

**Comment by StrahinjaJacimovic** [comment]
Hello Kevin,

You can check the following repository:
https://github.com/MikroElektronika/mikrosdk_v2

`log.h` file is located in `api/log/lib/include` folder.

Regards.
