### ISSUE TITLE
ECG/GSR Click did not work on GSR feature

### ISSUE THREAD

**Issue by AnhNhan2803** [MikroElektronika/mikrosdk_click_v2#49]
Hi team,

I'm Nhan, I just bought an ECG/GSR Click device, using the example code from the mikroSDK (https://github.com/MikroElektronika/mikrosdk_click_v2/tree/master/clicks/ecggsr). 

Currently, I can communicate with the device via I2C, read back device ID, get SPO2 and ECG data correctly from the device. However, when I switch to collect the GSR data, the device always returns 16383 which is actually an invalid value. By reading the schematic to get more information about the hardware design of GSR, I see that only one line from 3.5mm jack cable connect to GPIO_1 for Analog reading, which mean that I need to inject a current to my skin, and collect back the signal from the 3.5 cable connect to GSR port, but this setup did not work. 

Then, I am curious about the setup for GSR measurement using this device.

Thank you very much

**Comment by MarkoZiv** [comment]
Hi Nhan,
assigning @StefanFilipovic15 is going to assist you with this one.
Regards

**Comment by StefanFilipovic15** [comment]
Hello Nhan,

Could you please open a ticket on our [technical support](https://helpdesk.mikroe.com/) channel and describe there the issue in more detail, what type of MCU, dev board, and GSR sensors you are using, and how you connect everything, maybe attach some pictures as well? They will try to assist you in finding the easiest way to test your hardware.

Kind regards,
Stefan
