### ISSUE TITLE
How to use NFC 4 Click board with ESP32 using esp-idf framework?

### ISSUE THREAD

**Issue by amitabhskrishworks** [MikroElektronika/mikrosdk_click_v2#81]
I want to detect NFC tag using NFC 4 Click board and send the tag data to the ESP32 via SPI communication.
I need resources / library which can help me in running the nfc board on esp-idf framework

**Comment by StefanFilipovic15** [comment]
Hello,
Unfortunately, we do not provide libraries compatible with the ESP-IDF framework.
Check out [this](https://github.com/MikroElektronika/mikrosdk_click_v2/tree/master/clicks/nfc4) library source code, it might be a good starting point reference for you to make your library for ESP32.
