### ISSUE TITLE
Can 3 isolator click on Arduino

### ISSUE THREAD

**Issue by tekflio** [MikroElektronika/mikrosdk_click_v2#89]
Hi, I'm working with a Teensy 4.0 and a Esp32-S3 on Arduino IDE and I've just purchased a 'Can 3 isolator click board'.
I succeeded to use the click with the ACAN-T4 library on the Teensy, and I'm gonna try it with the Esp32 too.
But I'd like to use the native library you provide on [here](https://libstock.mikroe.com/projects/view/5361/can-isolator-3-click) in order to use two standard serial pins instead the CTX/CRX (specific for CAN communication).

So, is there a way to use that library directly on Arduino IDE ?

Thanks

**Comment by StefanFilipovic15** [comment]
Hello,

All libraries for click boards are written in [mikroSDK v2](https://github.com/MikroElektronika/mikrosdk_v2).
Unfortunately, there's no mikroSDK v2 porting layer for Arduino IDE yet implemented.
I'd suggest you refer to [this ](https://docs.mikroe.com/mikrosdk/user-manual/porting-guides/porting-to-3rd-party/)user guide for more information.

Kind regards,
Stefan Filipovic
