### ISSUE TITLE
UWB Click with ESP in TDOA mode

### ISSUE THREAD

**Issue by HardX18** [MikroElektronika/mikrosdk_click_v2#97]
Hi,

I am working on a project that requires multiple UWB Clicks to work together without any issues or delays. Upon conducting some research, I discovered that the available UWB library utilizes the TWR protocol, which restricts the usage to only one click at a time.

Is it possible to utilize the UWB Click in the TDoA protocol using the provided library?

If it is possible, could you please provide any sample code for that? It would be greatly appreciated and very helpful for my research.

**Comment by StefanFilipovic15** [comment]
Hello,

Our example for UWB click is more like a simple RX/TX example, it doesn't demonstrate any UWB localization.
You may find [these](https://github.com/Decawave/uwb-apps/tree/master) examples useful for your project.

Kind regards,
Stefan Filipovic
